### PR TITLE
Config file

### PR DESCRIPTION
**Pull request by AnonymousRandomPerson**

### CODE REVIEW

**Comment by Keopha** [comment]
Okay so I have a few questions, can you explain me these : 
pixelmon.config.legendarySpawnTicks=Legendary spawn ticks
pixelmon.config.legendaryRepeatSpawnTicks=Legendary repeat spawn ticks
pixelmon.config.hiddenAbilitySpawnRate=Hidden Ability spawn rate
Scale grass battle levels to player < Grass Battle = wild battle ?
pixelmon.config.awardPhotos=Award photos to wild battle winners 
pixelmon.config.namePlateRange=Name plate distance
pixelmon.config.enablePointToSteer=Enable point to steer
pixelmon.config.afkActivateSeconds=AFK activate seconds
pixelmon.config.afkHandlerTurnSeconds=AFK turn seconds

I stopped in my translation there because I'm running out of time, but I think I will ask you more questions in the future :> sorry ! But I need you to help me on those features because I can't test them or take a look at it since the version hasn't been released yet :<

**Comment by AnonymousRandomPerson** [comment]
The vast majority of these config settings are already in public mod versions, so the [Pixelmon wiki](http://pixelmonmod.com/wiki/index.php?title=Config) already has these settings documented. Just search the page for the lang code (e.g., "legendarySpawnTicks") to find the setting's description.

**Comment by Keopha** [comment]
Thanks for answering ! I'm doing that right now
Problem : What is that thing with pixelmon dropping photos ? I can't find anything about this :/

**Comment by Keopha** [comment]
Oh, just found a mistake : pixelmon.config.breedingEnviromentCheckSeconds=Seconds between environment checks
Isn't it supposed to be "pixelmon.config.breedingEnviroNmentCheckSeconds" ?

**Comment by AnonymousRandomPerson** [comment]
Fixed.

**Comment by Keopha** [comment]
Great :) Just, can you tell me what is the thing about pixelmon dropping photos ? :)

**Comment by AnonymousRandomPerson** [comment]
http://pixelmonmod.com/wiki/index.php?title=Photo

**Comment by Keopha** [comment]
Ohhh
Thanks for answering, sorry to be that boring :D 
I think the translation might be finished.. tomorrow, or in 2 days if I don't move my ass 0.o

**Comment by Keopha** [comment]
Hello ! Sorry again :D what does "via main spawner" means in "pixelmon.config.legendaryRepeatSpawnTicks.comment=" ? Is this pixelmon spawner ?

**Comment by AnonymousRandomPerson** [comment]
I believe that means natural spawning (i.e., NOT the Pixelmon spawner block).

**Comment by Keopha** [comment]
Okay ty !

**Comment by Keopha** [comment]
"pixelmon.config.timedLootReuseSeconds.comment=" a bracket is opened and not closed

**Comment by AnonymousRandomPerson** [comment]
Thanks, fixed.

**Comment by Keopha** [comment]
I was wondering, SMD reffers to someone, right ?

**Comment by JamieS1211** [comment]
SMD is the file type of exported animated models

**Comment by Keopha** [comment]
Ow
Okay thanks !

**Pull request merged**
