### PR TITLE
Update fr_FR.lang

### PR DESCRIPTION
**Pull request by Keopha**
BTW Is there a way to get the latest pixelmon version, the one with the latest features that we can find in the .lang files ? Because sometime i'm not sure of the translation to look at it in game !

### CODE REVIEW

**Comment by isiliden** [comment]
Generally we'll try to get the language files ready before release, so if you're watching the repo you can be notified of any changes by us.

**Comment by Keopha** [comment]
Yes that's not the problem ^^ I saw that, but for example, (in my translation) the line 5062 "gui.model.frame=Frame" I don't know how to translate frame, because it has many translation, that's why i'd like to see what it's refers to in the game, in a way to translate it better :)
Date: Wed, 6 Jan 2016 05:21:48 -0800

**Comment by AnonymousRandomPerson** [comment]
"Frame" here refers to a certain frame of an animation.

**Comment by Keopha** [comment]
Mhh okay thanks i'm gonna try my best then

**Pull request merged**
